### PR TITLE
 it is the telephone number validator

### PR DESCRIPTION
**Pull request by fatiabdulahi**
it's the telephone number validator I worke index.html styles.css script .js

### CODE REVIEW

**Comment by fatiabdulahi** [comment]
@sharifarezaie hello dear sharifa I compleated my project please review and shear your opinian .thank you

**Comment by Sharifarezaie** [comment]
Hi Fatima jan
Thanks for  mention me
I Thank you  project  good
I can aproved  your  project
Good jab👩‍💻🥳💯🎊

**Comment by fatiabdulahi** [comment]
@ahzamir hello dear Sir; I hope you are doing well I compleated my project  and my partner aproved if you have any time  please review and shear your opinian ,thank you

**Comment by ahzamir** [comment]
- Your project has so many issues:
  - Your branch has a conflict you have to solve the conflict first then ask for review.
  - Your README file has the info on your palindrome checker project you need to solve them and then ask for a review.
  - After you finished and solved all of these issues ask your partner to check your project and provide you a feedback and if she approved then ask me again.

@Sharifarezaie 

- Why you approve without checking her project.

**Comment by fatiabdulahi** [comment]
Thank you for your feedback dear Sir I well check

**Comment by fatiabdulahi** [comment]
@Sharifarezaie hello dear sharifa ; I solved my some problem please review and shear your opinian,

**Comment by fatiabdulahi** [comment]
@Sharifarezaie dear sharifa please review and shear your opinian

**Comment by fatiabdulahi** [comment]
@ahzamir hello dear Sir ,I hope you are doing well .I sloved your fedback issue please review and shear your opinian .thank you

**Comment by Sharifarezaie** [comment]
Hi Thanks for  mention  me
Your project  have not problems

You can merge  pull request 🥳❤

**Review by ahzamir — CHANGES_REQUESTED** [review]
@fatiabdulahi 

- Well done you solved the conflict issue and also your project functionality is perfect
- Your design is also great:
image

- Just in the mobile version your project has some issues please solve them and mention me here again so I can provide you a re-review:
image

**Comment by fatiabdulahi** [comment]
@ahzamir Hello dear Sir I hope you are doing well, thank you for your feedback . I solved  the issue .please review and shear your opinian .thank you

**Comment by ahzamir** [comment]
@fatiabdulahi 

- Your project still has the same issue, please don't submit with the same problem again and again without checking it.

image

**Comment by fatiabdulahi** [comment]
@ahzamir hello dear Sir thank you for your feedback .I solved issue my project please review and shear your opinion. Thank you

**Review by ahzamir — APPROVED** [review]
### Hi @fatiabdulahi 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image]image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Telephone Number Validator project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
